version: '3.1'

services:
  database:
    container_name: url_shortener_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: url_shortener_db
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
  swagger_ui:
    image: swaggerapi/swagger-ui
    container_name: "url_shortener_swagger"
    ports:
      - "8092:8080"
    volumes:
      - ./swagger/openapi.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json
